apiVersion: v1
kind: Pod
metadata:
 name: gpu-pod
spec:
 restartPolicy: OnFailure
 runtimeClassName: nvidia
 containers:
   - name: cuda-container
     image: docker.io/ncote/osgl-test:latest
     resources:
       limits:
         nvidia.com/gpu: 1 # requesting 1 GPU
     env:
       - name: NVIDIA_DRIVER_CAPABILITIES
         value: 'all'