apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.webapp.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.webapp.name }}
    group: {{ .Values.webapp.group }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.webapp.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.webapp.name }}
    spec:
      runtimeClassName: nvidia
      containers:
      - name: {{ .Values.webapp.name }}
        image: {{ .Values.webapp.container.image }}
        resources:
          limits:
            memory: {{ .Values.webapp.container.memory }}
            cpu: {{ .Values.webapp.container.cpu }}
            nvidia.com/gpu: 1 # requesting 1 GPU
        env:
          - name: NVIDIA_DRIVER_CAPABILITIES
            value: 'all'
          - name: NVIDIA_VISIBLE_DEVICES
            value: 'all'
          - name: ENV_NAME
            value: 'vapor'
        ports:
        - containerPort: {{ .Values.webapp.container.port }}